
package com.zeone.datalink.webservice.service.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VehicleInfoCXF", targetNamespace = "http://cxf.service.webservice.dataLink.zeone.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VehicleInfoCXF {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendVehicleWeight", targetNamespace = "http://cxf.service.webservice.dataLink.zeone.com/", className = "com.zeone.datalink.webservice.service.cxf.SendVehicleWeight")
    @ResponseWrapper(localName = "sendVehicleWeightResponse", targetNamespace = "http://cxf.service.webservice.dataLink.zeone.com/", className = "com.zeone.datalink.webservice.service.cxf.SendVehicleWeightResponse")
    public String sendVehicleWeight(@WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
